## Cosine Similarity

In [1]:
# Cosine Similarity
# Using Cosine Similarity to Build a Movie Recommendation System

In [24]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
# CSV loaded into a Dataframe

df = pd.read_csv('movie_dataset.csv')

In [26]:

df.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [27]:
# Data preprocessing and replace any rows having NaN values with a space/empty string

In [28]:
features = ['keywords', 'cast', 'genres', 'director']

In [29]:
for feature in features:
    
    df[feature] = df[feature].fillna('')

In [30]:
# Combined features in a single string

In [31]:
def combined_features(row):
    
    return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']

In [32]:
df["combined_features"] = df.apply(combined_features, axis=1)

In [33]:
# extracting features 
# now we will extract features from our data

In [34]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])

In [35]:
print ("Count Matrix: ", count_matrix.toarray())

Count Matrix:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [36]:
# Using the Cosine Similarity
# Cosine similarity from Sklearn, as the matric to compute the similarity between two movies
# 0 means no similarity, where as 1 neames that both the item are 100% similar

In [37]:
# Python Cosine Similarity or cosine kernel, computes similarity as the normalized dot product of input samples X and Y
# we will use sklearn cosine_similarity to find the cos theta for the two vectors in the count matrix 

In [39]:
cosine_sim = cosine_similarity(count_matrix)

In [43]:
cosine_sim

array([[1.        , 0.10540926, 0.12038585, ..., 0.        , 0.        ,
        0.        ],
       [0.10540926, 1.        , 0.0761387 , ..., 0.03651484, 0.        ,
        0.        ],
       [0.12038585, 0.0761387 , 1.        , ..., 0.        , 0.11145564,
        0.        ],
       ...,
       [0.        , 0.03651484, 0.        , ..., 1.        , 0.        ,
        0.04264014],
       [0.        , 0.        , 0.11145564, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04264014, 0.        ,
        1.        ]])

In [ ]:
# Content User Likes
# Next step is to take a input a movie that the user likes in the movie_user_likes variable

In [44]:
movie_user_likes = "Dead Poets Society"

In [45]:
def get_index_from_title(title):
    
    return df[df.title == title]["index"].values[0]

In [47]:
movie_index = get_index_from_title(movie_user_likes)

In [50]:
movie_index

2453

In [51]:
# Generate the Similar Movie Matrix

In [52]:
similar_movies = list(enumerate(cosine_sim[movie_index]))

In [62]:
#similar_movies

In [ ]:
# Sorting the Similar Movies List in Descending Order

In [57]:
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

In [61]:
#sorted_similar_movies

In [ ]:
# The sorted_similar_movies will be a list of all the movies sorted in descending order with respect to their 
# similarity score with the input movie movie_user_likes

In [ ]:
# as we can see at the above, the most similar one with a similarity score of 0.99999999993 is at the top most
# with its index number 2453

In [ ]:
# Now print the Index Number -> Movie Title movie similar to one we have given as input to the system through
# movie_user_likes variable

In [ ]:
# Now we will print the 15 most similar movies from a pool of 4802 movies

In [59]:
def get_title_from_index(index):
    
    return df[df.index == index]["title"].values[0]

In [60]:
i = 0

for movie in sorted_similar_movies:
    
    print(get_title_from_index(movie[0]))
    
    i = i + 1
    
    if i > 15:
        
        break

Dead Poets Society
Much Ado About Nothing
Patch Adams
Good Will Hunting
Flightplan
Alive
The Basket
What Just Happened
Adulterers
The Sting
The Tree of Life
The Greatest Game Ever Played
Light It Up
The Wood
The Naked Ape
Jakob the Liar
